apiVersion: v1
kind: Service
metadata:
  name: {{ include "ureport.fullname" . }}-web
  labels:
    {{- include "ureport.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ureport.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
    {{- with .Values.extraSelectorLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
