apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ureport.fullname" . }}
  labels:
    {{- include "ureport.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secretEnvVariables }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
